#!/usr/bin/env python3
"""
Generates fonts.h: anti-aliased (4-bit alpha) bitmap fonts for the TFT.

    python3 tools/gen_fonts.py          # writes ../fonts.h

Needs Pillow and the Noto Sans / Ubuntu fonts (Ubuntu desktop ships both).
"""

import os

from PIL import Image, ImageDraw, ImageFont

NOTO = "/usr/share/fonts/truetype/noto"
UBUNTU = "/usr/share/fonts/truetype/ubuntu"

# name, file, pixel size, characters
FONTS = [
    ("font_small", f"{NOTO}/NotoSans-Regular.ttf", 13, None),
    ("font_body",  f"{NOTO}/NotoSans-Bold.ttf",    16, None),
    ("font_title", f"{NOTO}/NotoSans-Bold.ttf",    24, None),
    ("font_huge",  f"{UBUNTU}/Ubuntu-L.ttf",       60, "-./0123456789:"),
]

ASCII = "".join(chr(c) for c in range(32, 127))

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "fonts.h")


def render_glyph(font, ch):
    left, top, right, bottom = font.getbbox(ch)
    w, h = max(right - left, 0), max(bottom - top, 0)
    advance = round(font.getlength(ch))

    if w == 0 or h == 0:
        return {"w": 0, "h": 0, "x": 0, "y": 0, "adv": advance, "data": b""}

    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=255)

    # 4-bit alpha, two pixels per byte, rows padded to whole bytes
    data = bytearray()
    for y in range(h):
        row = [img.getpixel((x, y)) >> 4 for x in range(w)]
        if len(row) % 2:
            row.append(0)
        for i in range(0, len(row), 2):
            data.append((row[i] << 4) | row[i + 1])

    return {"w": w, "h": h, "x": left, "y": top, "adv": advance, "data": bytes(data)}


def main():
    out = [
        "/* Generated by tools/gen_fonts.py - do not edit */",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    uint32_t offset;     /* into the font's bitmap */",
        "    uint8_t  width;",
        "    uint8_t  height;",
        "    int8_t   x_offset;",
        "    int8_t   y_offset;   /* from the top of the line */",
        "    uint8_t  advance;",
        "} glyph_t;",
        "",
        "typedef struct {",
        "    const uint8_t *bitmap;   /* 4-bit alpha, rows padded to bytes */",
        "    const glyph_t *glyphs;",
        "    char first;",
        "    char last;",
        "    uint8_t height;          /* line height */",
        "    uint8_t ascent;",
        "} font_t;",
        "",
    ]

    total = 0

    for name, path, size, chars in FONTS:
        font = ImageFont.truetype(path, size)
        ascent, descent = font.getmetrics()
        chars = chars or ASCII
        first, last = chars[0], chars[-1]

        bitmap = bytearray()
        glyphs = []

        for code in range(ord(first), ord(last) + 1):
            ch = chr(code)
            g = render_glyph(font, ch) if ch in chars else \
                {"w": 0, "h": 0, "x": 0, "y": 0, "adv": 0, "data": b""}
            glyphs.append((len(bitmap), g))
            bitmap += g["data"]

        total += len(bitmap)

        out.append(f"static const uint8_t {name}_bitmap[{len(bitmap)}] = {{")
        for i in range(0, len(bitmap), 20):
            out.append("    " + ", ".join(f"0x{b:02X}" for b in bitmap[i:i + 20]) + ",")
        out.append("};")
        out.append("")

        out.append(f"static const glyph_t {name}_glyphs[] = {{")
        for (offset, g), code in zip(glyphs, range(ord(first), ord(last) + 1)):
            label = chr(code) if chr(code) not in "\\*/" else f"0x{code:02X}"
            out.append(f"    {{ {offset}, {g['w']}, {g['h']}, {g['x']}, {g['y']}, {g['adv']} }}, /* {label} */")
        out.append("};")
        out.append("")

        out.append(f"static const font_t {name} = {{")
        out.append(f"    {name}_bitmap, {name}_glyphs, '{first}', '{last}', {ascent + descent}, {ascent}")
        out.append("};")
        out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))

    print(f"Wrote {os.path.normpath(OUT)} ({total} bytes of glyph data)")


if __name__ == "__main__":
    main()
